name: Python CI
# Trigger the worflow on any push to the main branch or pull request
# Defining the events on which the workflow gets triggered
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest # Container on which our application will run

        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'
            
            - name: Install dependencies
              run: |
                curl -LsSf https://astral.sh/uv/install.sh | sh
                uv add -r requirements.txt
                
            - name: Run tests
              run: python -m pytest
